// Code generated by gobee. DO NOT EDIT.
//
// Typed accessors for the BPF programs and maps declared in sockops.go.
// Use LoadSockops with a *ebpf.CollectionSpec to populate this struct;
// access programs and maps via objs.<Name> instead of
// coll.Programs["<name>"] / coll.Maps["<name>"].

package bpf

import (
	"errors"
	"fmt"
	"strings"

	"github.com/cilium/ebpf"

	bpfvetanalyzer "github.com/boratanrikulu/bpfvet/pkg/analyzer"
	bpfvetversion "github.com/boratanrikulu/bpfvet/pkg/version"
	"golang.org/x/sys/unix"

	"github.com/boratanrikulu/gobee/diagnose"
)

// SockopsPrograms holds one *ebpf.Program per //bpf:section function.
type SockopsPrograms struct {
	GecitSockops *ebpf.Program `ebpf:"GecitSockops"`
}

// SockopsMaps holds one *ebpf.Map per package-level map declaration.
type SockopsMaps struct {
	ConfigMap   *ebpf.Map `ebpf:"ConfigMap"`
	ConnEvents  *ebpf.Map `ebpf:"ConnEvents"`
	Connections *ebpf.Map `ebpf:"Connections"`
	ExcludeIps  *ebpf.Map `ebpf:"ExcludeIps"`
	TargetPorts *ebpf.Map `ebpf:"TargetPorts"`
}

// SockopsObjects bundles every program and map for one transpilation unit.
type SockopsObjects struct {
	SockopsPrograms
	SockopsMaps
}

// Close releases every map and program owned by o.
func (o *SockopsObjects) Close() error {
	var errs []error
	if o.ConfigMap != nil {
		errs = append(errs, o.ConfigMap.Close())
	}
	if o.ConnEvents != nil {
		errs = append(errs, o.ConnEvents.Close())
	}
	if o.Connections != nil {
		errs = append(errs, o.Connections.Close())
	}
	if o.ExcludeIps != nil {
		errs = append(errs, o.ExcludeIps.Close())
	}
	if o.TargetPorts != nil {
		errs = append(errs, o.TargetPorts.Close())
	}
	if o.GecitSockops != nil {
		errs = append(errs, o.GecitSockops.Close())
	}
	return errors.Join(errs...)
}

// LoadSockops populates a fresh SockopsObjects from spec. Before loading the
// program into the kernel, it asks bpfvet what kernel version the
// spec needs and compares against the running kernel. After loading,
// any *ebpf.VerifierError is annotated with Go source positions from
// the embedded sourcemap.
func LoadSockops(spec *ebpf.CollectionSpec) (*SockopsObjects, error) {
	if err := checkSockopsKernel(spec); err != nil {
		return nil, err
	}
	objs := &SockopsObjects{}
	if err := spec.LoadAndAssign(objs, nil); err != nil {
		return nil, annotateSockopsVerifierErr(err)
	}
	return objs, nil
}

// SockopsSourceMap is the C-line → Go-position table for sockops.bpf.c. It's
// embedded so LoadSockops can annotate verifier errors without shipping
// the .map file alongside the binary.
var SockopsSourceMap = `# gobee sourcemap. Format: <c-line>\t<go-file>:<go-line>:<go-col>
10	pkg/ebpf/bpf/src/sockops.go:29:6
18	pkg/ebpf/bpf/src/sockops.go:39:6
27	pkg/ebpf/bpf/src/sockops.go:50:6
33	pkg/ebpf/bpf/src/sockops.go:62:5
40	pkg/ebpf/bpf/src/sockops.go:63:5
47	pkg/ebpf/bpf/src/sockops.go:64:5
54	pkg/ebpf/bpf/src/sockops.go:65:5
60	pkg/ebpf/bpf/src/sockops.go:66:5
67	pkg/ebpf/bpf/src/sockops.go:68:1
68	pkg/ebpf/bpf/src/sockops.go:69:2
69	pkg/ebpf/bpf/src/sockops.go:70:2
70	pkg/ebpf/bpf/src/sockops.go:71:2
71	pkg/ebpf/bpf/src/sockops.go:72:3
73	pkg/ebpf/bpf/src/sockops.go:75:2
74	pkg/ebpf/bpf/src/sockops.go:76:2
75	pkg/ebpf/bpf/src/sockops.go:77:2
76	pkg/ebpf/bpf/src/sockops.go:78:3
78	pkg/ebpf/bpf/src/sockops.go:81:2
79	pkg/ebpf/bpf/src/sockops.go:82:2
80	pkg/ebpf/bpf/src/sockops.go:84:2
81	pkg/ebpf/bpf/src/sockops.go:85:2
82	pkg/ebpf/bpf/src/sockops.go:86:2
83	pkg/ebpf/bpf/src/sockops.go:87:2
84	pkg/ebpf/bpf/src/sockops.go:88:2
85	pkg/ebpf/bpf/src/sockops.go:89:2
86	pkg/ebpf/bpf/src/sockops.go:90:2
87	pkg/ebpf/bpf/src/sockops.go:91:2
88	pkg/ebpf/bpf/src/sockops.go:93:2
89	pkg/ebpf/bpf/src/sockops.go:94:2
90	pkg/ebpf/bpf/src/sockops.go:95:2
91	pkg/ebpf/bpf/src/sockops.go:97:2
92	pkg/ebpf/bpf/src/sockops.go:98:2
93	pkg/ebpf/bpf/src/sockops.go:100:2
96	pkg/ebpf/bpf/src/sockops.go:103:1
97	pkg/ebpf/bpf/src/sockops.go:104:2
98	pkg/ebpf/bpf/src/sockops.go:105:2
101	pkg/ebpf/bpf/src/sockops.go:108:1
102	pkg/ebpf/bpf/src/sockops.go:109:2
103	pkg/ebpf/bpf/src/sockops.go:110:2
104	pkg/ebpf/bpf/src/sockops.go:111:2
105	pkg/ebpf/bpf/src/sockops.go:112:3
107	pkg/ebpf/bpf/src/sockops.go:114:2
108	pkg/ebpf/bpf/src/sockops.go:115:3
110	pkg/ebpf/bpf/src/sockops.go:118:2
111	pkg/ebpf/bpf/src/sockops.go:120:2
112	pkg/ebpf/bpf/src/sockops.go:121:3
113	pkg/ebpf/bpf/src/sockops.go:122:3
114	pkg/ebpf/bpf/src/sockops.go:123:4
116	pkg/ebpf/bpf/src/sockops.go:125:3
117	pkg/ebpf/bpf/src/sockops.go:127:3
118	pkg/ebpf/bpf/src/sockops.go:129:3
119	pkg/ebpf/bpf/src/sockops.go:130:3
120	pkg/ebpf/bpf/src/sockops.go:132:3
122	pkg/ebpf/bpf/src/sockops.go:135:2
125	pkg/ebpf/bpf/src/sockops.go:139:1
127	pkg/ebpf/bpf/src/sockops.go:140:2
128	pkg/ebpf/bpf/src/sockops.go:141:2
129	pkg/ebpf/bpf/src/sockops.go:142:2
130	pkg/ebpf/bpf/src/sockops.go:143:3
132	pkg/ebpf/bpf/src/sockops.go:145:2
133	pkg/ebpf/bpf/src/sockops.go:146:3
135	pkg/ebpf/bpf/src/sockops.go:149:2
136	pkg/ebpf/bpf/src/sockops.go:150:2
137	pkg/ebpf/bpf/src/sockops.go:151:3
139	pkg/ebpf/bpf/src/sockops.go:153:2
140	pkg/ebpf/bpf/src/sockops.go:154:3
142	pkg/ebpf/bpf/src/sockops.go:156:2
143	pkg/ebpf/bpf/src/sockops.go:157:3
145	pkg/ebpf/bpf/src/sockops.go:160:2
`

// annotateSockopsVerifierErr wraps err. If err is a *ebpf.VerifierError,
// every C-line reference in the verifier log is annotated with the
// matching Go source position. Other errors pass through unchanged.
func annotateSockopsVerifierErr(err error) error {
	var verr *ebpf.VerifierError
	if !errors.As(err, &verr) {
		return err
	}
	sm, perr := diagnose.ParseSourceMapBytes([]byte(SockopsSourceMap))
	if perr != nil {
		return err // sourcemap parse failed; keep the original error
	}
	annotated := diagnose.AnnotateLines(verr.Log, sm)
	return fmt.Errorf("%w\n\n----- annotated verifier log -----\n%s", err, strings.Join(annotated, "\n"))
}
func checkSockopsKernel(spec *ebpf.CollectionSpec) error {
	rep, err := bpfvetanalyzer.AnalyzeSpec(spec)
	if err != nil || rep == nil {
		return nil // can't analyze; fall through to LoadAndAssign for a real error
	}
	running, ok := runningKernel()
	if !ok || !running.Less(rep.MinKernel) {
		return nil
	}
	return fmt.Errorf("bpf program needs kernel >= %s, host is %s", rep.MinKernel, running)
}

// runningKernel parses /proc/sys/kernel/osrelease via uname(2) and
// returns the host's kernel as a bpfvet KernelVersion. Returns
// ok=false on any parse failure so callers fall through to the
// regular load path.
func runningKernel() (bpfvetversion.KernelVersion, bool) {
	var u unix.Utsname
	if err := unix.Uname(&u); err != nil {
		return bpfvetversion.KernelVersion{}, false
	}
	release := unix.ByteSliceToString(u.Release[:])
	var major, minor int
	if _, err := fmt.Sscanf(release, "%d.%d", &major, &minor); err != nil {
		return bpfvetversion.KernelVersion{}, false
	}
	return bpfvetversion.V(major, minor), true
}

// User-defined types from the kernel-side program. Layout matches
// the kernel struct so encoding/binary on the userspace side and
// clang's struct layout in the kernel agree byte-for-byte.

type Config struct {
	MSS               uint16
	RestoreMSS        uint16
	RestoreAfterBytes uint32
	Enabled           uint8
	Reserved          [7]uint8
}

type ConnEvent struct {
	SrcIP   uint32
	DstIP   uint32
	SrcPort uint16
	DstPort uint16
	Seq     uint32
	Ack     uint32
}

type ConnState struct {
	BytesSent   uint32
	MssRestored uint8
	Reserved    [3]uint8
}

// Constants mirrored from the kernel-side program. Capitalized so
// userspace can reference them directly (kernel-side names may be
// unexported; the bindings always export them).
const (
	IpprotoTCP = 6
	TcpMaxSeg  = 2
)
